routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/admin');
});

Route::get('login', function () {
    return redirect('/admin');
});

// Authentication Routes...
Route::get('admin', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('admin', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
/*$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');*/

//TODO: middleware, prefix
Route::resource('users', 'Admin\UserController');

app/Models/SmsVerification.php
<?php
namespace App\Model;

use App\User;
use Illuminate\Database\Eloquent\Model;

class  SmsVerification extends Model
{
    protected $table = 'sms_verifications';

    public $fillable = ['user_id', 'validation'];

    /**
     * Get the phone record associated with the user.
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/User.php
<?php

namespace App;

use App\Model\SmsVerification;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use jeremykenedy\LaravelRoles\Traits\HasRoleAndPermission;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, HasRoleAndPermission,HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone', 'sex', 'invite_type','sms_verified_at'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'sms_verified' => 'datetime',
    ];


    /**
     * Get the phone record associated with the user.
     */
    public function smsValidation()
    {
        return $this->hasOne(SmsVerification::class);
    }

}

app/Http/Controllers/API/RegisterController.php
<?php

namespace App\Http\Controllers\API;

use App\Classes\SMSRU;
use App\Model\SmsVerification;
use App\Repositories\Interfaces\UserApiRegistrationRepositoryInterface;
use App\Repositories\UserApiRegistrationRegistration;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class RegisterController
{
    const CODE = 1111;

    private $apiRepository;

    public function __construct(UserApiRegistrationRegistration $userApi)
    {
        $this->apiRepository = $userApi;
    }

    public function register(Request $request)
    {
        $smsru = new SMSRU(config('app.sms_ru_key'));
        $data = new \stdClass();
        $data->to = request('phone');

        //$code = $this->generateCode();
        $code = self::CODE;

        $user = $this->storeUser();
        $result = $this->storeVerificationCode($user, $code);

        $data->text = 'Your SMS verification code is: ' . $code;
//        $sms = $smsru->send_one($data);
//
//        if ($sms->status == "OK") {
//            return response()->json(['data' => $result], Response::HTTP_OK);
//
//        } else {
//            //return "Сообщение не отправлено. ";
//
//            /*echo "Код ошибки: $sms->status_code. ";*/
//            return "Текст ошибки: $sms->status_text.";
//        }

        return response()->json(['data' => $result], Response::HTTP_OK);

    }

    private function storeUser()
    {
        return $this->apiRepository->storeUser();
    }

    public function storeVerificationCode($user, $code)
    {
        return $this->apiRepository->storeVerificationCode($user, $code);
    }

    public function validateSmsCode()
    {
        return $this->apiRepository->validateSmsCode();
    }

    private function generateCode()
    {
        $code = mt_rand(111111, 999999);
        return $code;
    }


}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UpdateUserRequest;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Repositories\UserRepository;

class UserController extends Controller
{
    private $userRepository;

    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = $this->userRepository->all();

        return view('admin.dashboard', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //TODO: add validation

    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->userRepository->edit($id);

        return view('admin.user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, $id)
    {
        $this->userRepository->update($request, $id);

        return redirect('/users');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->userRepository->destroy($id);

        return redirect()->route('users.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
       //
    }
}

resources/views/admin/dashboard.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-9 offset-1">
                <table id="users" class="table table-striped table-bordered table-sm text-center" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th class="th-sm">Id</th>
                        <th class="th-sm">Phone</th>
                        <th class="th-sm">Sex</th>
                        <th class="th-sm">Invite</th>
                        <th class="th-sm">Edit </th>
                        <th class="th-sm">Delete</th>
                        <th class="th-sm">Accepted</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>{{ $user->id }}</td>
                            <td>{{ $user->phone }}</td>
                            <td>{{ $user->sex }}</td>
                            <td>{{ $user->invite_type }}</td>
                            <td><a href="{{ route('users.edit', $user->id) }}" class="btn btn-info">Edit</a></td>
                            <td>
                                <a class="btn btn-danger" onclick="onDeleteConfirm(this)"><i class="fa fa-trash"></i>Delete</a>
                                <form action="{{route('users.destroy', $user->id)}}" method="post">
                                    <input type="hidden" name="_method" value="delete"/>
                                    @csrf
                                </form>
                            </td>
                            <td>{{$user->sms_verified_at ? 'YES' : 'NO'}}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                {{ $users->links() }}
            </div>
        </div>
    </div>

@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form method="post" action="{{route('users.update', ['user'=>$user])}}">
            @csrf
            <input name="_method" type="hidden" value="PUT">
            <div class="form-group">
                <label for="phone">Phone number</label>
                <input name="phone" class="form-control" id="phone" value="{{$user->phone}}">
                @error('phone') <span class="text-danger">{{ $message }}</span>@enderror
            </div>
            <div class="form-group">
                <label for="sex">Sex</label>
                <select name="sex" id="sex" class="form-control">
                    <option @if($user->sex === 'male') selected @endif value="male">Male</option>
                    <option @if($user->sex === 'female') selected @endif value="female">Female</option>
                </select>
                @error('sex') <span class="text-danger">{{ $message }}</span>@enderror
            </div>
            <div class="form-group">
                <label for="invite_type">Invite Type</label>
                <select name="invite_type" id="invite_type" class="form-control">
                    <option @if($user->invite_type === 'accept') selected @endif value="accept">Accept</option>
                    <option @if($user->invite_type === 'send') selected @endif value="send">Send</option>
                </select>
                @error('invite_type') <span class="text-danger">{{ $message }}</span>@enderror
            </div>
            <div class="form-group">
                <label for="sms_verified">Verified</label>
                <select name="sms_verified_at" id="sms_verified" class="form-control">
                    <option @if(!is_null($user->sms_verified_at)) selected @endif value="1">Yes</option>
                    <option @if(is_null($user->sms_verified_at)) selected @endif value="0">No</option>
                </select>
                @error('sms_verified_at') <span class="text-danger">{{ $message }}</span>@enderror
            </div>
            <div class="row">
                <button type="submit" class="btn btn-success">Submit</button>
                <a type="button" href="{{ route('users.index') }}" class="btn btn-secondary ml-2">Back</a>
            </div>
        </form>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

    </div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/custom.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>